/**
 * @description: This class is used to create a new Account record with the name 'newsc1'.
 */
public with sharing class sdfsdfsdfsd {
    /**
     * @description: This method creates a new Account record with the name 'newsc1' and inserts it into the database.
     */
    public void accountowner() {
        Account acclist = new Account();
        acclist.Name = 'newsc12';
        insert acclist;
    }
}